stage ('Stage 1. checkout repo')

node ('docker') {
        git 'https://github.com/iambowen/microservices-training-lesson-7-testing-pact.git'
}

stage 'Stage 2. test and build' 
parallel ( 
'unit test' : {
    node ('docker') { sh './event-service/auto/unit_test.sh' }
}, 
"pact tests" : {
    node ('docker')  { sh 'echo pact tests' }
}, 
"build image" : {
    node ('docker') { sh 'echo build docker image' }    
}
)

stage "Stage 3. deploy to e2e and integration test" 
    node ('docker')  { sh 'echo deploy to e2e env' }
    node ('docker')  { sh 'echo run e2e/integration tests' }

stage 'Stage 4. staging deployment'
    node ('docker')  { sh 'echo deploy to staging' }
    node ('docker')  { sh 'echo run performance tests'}

stage 'Stage 5. production deployment'
    node ('docker')  { sh 'echo deploy to production' }
    node ('docker')  { sh 'echo run smoke tests' }
