stage 'test and build'

parallel 'unit test' : {
    node 'docker' { sh 'echo unit tests' }
}, "pact tests" : {
    node 'docker' { sh 'echo pact tests' }
}, "build image" : {
    node 'docker' { sh 'echo build docker image' }    
}

stage "deploy to e2e and integration test" : {
    node 'docker' { sh 'echo deploy to e2e env' }
    node 'docker' { sh 'echo run e2e/integration tests' }
}

stage 'staging deployment': {
    node 'docker' { sh 'echo deploy to staging' }
    node 'docker' { sh 'echo run performance tests'}
}

stage 'production deployment': {
    node 'docker' { 'echo deploy to production' }
    node 'docker' { 'echo run smoke tests' }
}
