eureka:
  client:
    registryFetchIntervalSeconds: 5
    leaseRenewalIntervalInSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
    enabled: false

server:
  port: ${PORT:${SERVER_PORT:9000}}   # Select any available port if neither port nor server port are specified.

---
spring:
  profiles: docker
  data:
    mongodb:
      host: mongo

server:
  port: 9000
  
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8010/eureka/
    enabled: false 
     
---
spring:
  profiles: pact-test
  data:
    mongodb:
      host: mongo

eureka:
  client:
    enabled: false